### ISSUE TITLE
安装报错error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_mWUon1/.INSTALL; post_upgrade 5.4.3-1 5.4.3-1 ) failed to execute correctly

### ISSUE THREAD

**Issue by vipzrx** [zeromake/msys2-packages#1]
$ pacman -U lua-5.4.3-1-x86_64.pkg.tar.zst
loading packages...
warning: lua-5.4.3-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) lua-5.4.3-1

Total Installed Size:  0.79 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                     [#####################] 100%
(1/1) checking package integrity                   [#####################] 100%
(1/1) loading package files                        [#####################] 100%
(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) reinstalling lua                             [#####################] 100%
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_mWUon1/.INSTALL; post_upgrade 5.4.3-1 5.4.3-1 ) failed to execute correctly

**Comment by zeromake** [comment]
@vipzrx 
我这边没有问题，可能因为用的 git-windows 的 msys2 编译的吧，你可以考虑自己编译
clone 下来
```bash
cd lua
makepkg
```

**Comment by vipzrx** [comment]
0 我用的msys2 从这里下载的 https://www.msys2.org/

你说的git -window 是这个吗? [Git for Windowshttps://gitforwindows.org](https://gitforwindows.org/)

1 虽然报错,但是能永.z.lua可以用.

```
❯ lua
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio

~ ❯ z /d/11/msys2-packages/lua
/d/11/msys2-packages/lua         /d/dl/msys2-packages-master/lua

```
2 我下载你的源码,编译 报错了.新开了一个issue #2
